import { ArtworkModel } from './artwork.model';

export const ArtworkMocks: ArtworkModel[] = [
  {
    id: 'dfghjkiuyfgbnj',
    creatorId: 'jmngt67u8iujhgty7ujh',
    price: 0.1,
    source: '/images/artwork/photo01.png',
    description: '2020, South America',
    title: 'Season 2, 32',
  },
  {
    id: 'jg7ew878hubugh',
    creatorId: 'jmngt67u8iujhgty7ujh',
    price: 0.1,
    source: '/images/artwork/photo02.png',
    description: '2022, North America',
    title: 'NA 2045',
  },
  {
    id: 'gfgujhgtyy7uijbhyj',
    creatorId: 'jmngt67u8iujhgty7ujh',
    price: 0.1,
    source: '/images/artwork/photo03.jpg',
    description:
      '2022. On-going conflict. Depicts a conflict between two groups driven by strong ideologies.',
    title: 'Outlands 223',
  },
  {
    id: 'gfrt67uijnhytgy78uij',
    creatorId: 'jmngt67u8iujhgty7ujh',
    price: 0.1,
    source: '/images/artwork/photo04.jpg',
    description: '2022, East Asia',
    title: 'Outlands 3',
  },
  {
    id: 'nhgt678uijnbytuj',
    creatorId: 'jmngt67u8iujhgty7ujh',
    price: 0.1,
    source: '/images/artwork/photo06.jpg',
    description: '2022. Dangerous situation in a remote region.',
    title: 'Deep Outer 224',
  },
  {
    id: 'nhgt678ijhgt67uj',
    creatorId: 'jmngt67u8iujhgty7ujh',
    price: 0.1,
    source: '/images/artwork/photo07.jpg',
    description: '2022, North America',
    title: 'Nightshade',
  },
  {
    id: 'hhgt678uijhyt78ujh',
    creatorId: 'jmngt67u8iujhgty7ujh',
    price: 0.1,
    source: '/images/artwork/photo08.jpg',
    description: '2019. Unchartered region of South America.',
    title: 'Gildered Issue',
  },
  {
    id: 'jnhy789oikjhy78ui',
    creatorId: 'jmngt67u8iujhgty7ujh',
    price: 0.1,
    source: '/images/artwork/photo09.jpg',
    description: '2023, Africa',
    title: 'SS04:03',
  },
  {
    id: 'jhgy78uijhgty78ujn',
    creatorId: 'jmngt67u8iujhgty7ujh',
    price: 0.1,
    source: '/images/artwork/photo10.png',
    description: '2021. On the ground during the pandemic in a hard-hit region.',
    title: 'Pandemic 22',
  },
].map((simpleMock) => ({
  ...simpleMock,
  slug: simpleMock.title.toLowerCase().split(' ').join('-'),
}));
